In [1]:
import pandas as pd

In [7]:
#시군구별 계약종별별 전력사용량	((단위 : kWh)) 불필요 열 제거
elect = pd.read_csv('./data/elect_2015_2024.csv',encoding='CP949')

# 강원도만 뽑기 
gangwon_elect = elect[elect['시도']=='강원도']
gangwon_elect['시군구'].unique()  # 18개 강원도 지역 포함

#기상청 데이터와 일치시키기 
gangwon_elect['지점명'] = gangwon_elect['시군구'].str.replace('시|군|구','',regex=True)
gangwon_elect = gangwon_elect.rename(columns={'연도':'years'})

# 기상청 데이터의 강원도 지역과 동일한 한국전력의 측정 지역 추출 (기상청 강원도 데이터의 지역수(9개 지역)가 더 적기 때문에 기준으로 진행)
gangwon_temp_list = ['속초', '철원', '춘천', '강릉', '동해', '원주', '영월', '인제', '홍천']

gangwon_elect_list = []
for i in gangwon_elect['시군구'].drop_duplicates():
    if i in gangwon_temp_list: # 기상청 강원도 리스트
        gangwon_elect_list.append(i)
gangwon_elect_list

# 강원도 지역의 속한 데이터프레임 뽑기 
gangwon_keyword = "|".join(gangwon_elect_list)
gangwon_elect = gangwon_elect[gangwon_elect['시군구'].str.contains(gangwon_keyword)].reset_index(drop=True)

# 2번째 방법
gangwon_elect = gangwon_elect[gangwon_elect['계약종별']=='합 계'].reset_index()
gangwon_elect

C:\Users\Playdata\AppData\Local\Temp\ipykernel_15876\1264224954.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gangwon_elect['지점명'] = gangwon_elect['시군구'].str.replace('시|군|구','',regex=True)

,index,Unnamed: 0,years,시도,시군구,계약종별,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,지점명
0,7,846,2017,강원도,춘천시,합 계,166196000,169291387,145015680,136939977,117793316,118446385,131735946,143301760,125533334,113838415,133117933,163759750,춘천
1,15,854,2017,강원도,원주시,합 계,241954655,247369210,215121760,198701065,170476054,174217260,186085568,197826912,182811359,161232783,198820548,237349114,원주
2,23,862,2017,강원도,강릉시,합 계,183639452,182721974,172538027,164644504,152269671,150949153,156001523,163335439,158143303,153297761,171109543,185695935,강릉
3,31,870,2017,강원도,동해시,합 계,228309916,208076848,230650616,224490296,233263356,221073970,221303715,222780159,201455297,228993738,228581415,222264978,동해
4,39,878,2017,강원도,태백시,합 계,31585822,32002624,28866689,28017437,24225875,23745594,22989416,23955090,24185298,23003159,27367970,31151748,태백
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,1407,17483,2024,강원도,화천군,합 계,29165031,28723930,23725784,20766399,16718436,17251210,18420531,21986435,21346321,18065309,19552575,24406547,화천
176,1415,17491,2024,강원도,양구군,합 계,23291257,22677827,19596164,17355817,14082733,14229768,14991945,17684967,17615061,14698927,17400592,19957358,양
177,1423,17499,2024,강원도,인제군,합 계,38109936,36868388,31533989,27993323,23516134,24137372,24907169,29372412,27596513,24236804,27041391,32852904,인제
178,1431,17507,2024,강원도,고성군,합 계,37165981,35544308,32327950,28477105,24692917,25638908,28443188,34147358,31185481,26318357,27676708,31487012,고성
179,1439,17515,2024,강원도,양양군,합 계,34541917,33319781,30703715,27322258,24223622,24661946,26379386,32251221,29372839,25051829,26809758,29944522,양양

In [8]:
gangwon_elect

,index,Unnamed: 0,years,시도,시군구,계약종별,1월,2월,3월,4월,5월,6월,7월,8월,9월,10월,11월,12월,지점명
0,7,846,2017,강원도,춘천시,합 계,166196000,169291387,145015680,136939977,117793316,118446385,131735946,143301760,125533334,113838415,133117933,163759750,춘천
1,15,854,2017,강원도,원주시,합 계,241954655,247369210,215121760,198701065,170476054,174217260,186085568,197826912,182811359,161232783,198820548,237349114,원주
2,23,862,2017,강원도,강릉시,합 계,183639452,182721974,172538027,164644504,152269671,150949153,156001523,163335439,158143303,153297761,171109543,185695935,강릉
3,31,870,2017,강원도,동해시,합 계,228309916,208076848,230650616,224490296,233263356,221073970,221303715,222780159,201455297,228993738,228581415,222264978,동해
4,39,878,2017,강원도,태백시,합 계,31585822,32002624,28866689,28017437,24225875,23745594,22989416,23955090,24185298,23003159,27367970,31151748,태백
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,1407,17483,2024,강원도,화천군,합 계,29165031,28723930,23725784,20766399,16718436,17251210,18420531,21986435,21346321,18065309,19552575,24406547,화천
176,1415,17491,2024,강원도,양구군,합 계,23291257,22677827,19596164,17355817,14082733,14229768,14991945,17684967,17615061,14698927,17400592,19957358,양
177,1423,17499,2024,강원도,인제군,합 계,38109936,36868388,31533989,27993323,23516134,24137372,24907169,29372412,27596513,24236804,27041391,32852904,인제
178,1431,17507,2024,강원도,고성군,합 계,37165981,35544308,32327950,28477105,24692917,25638908,28443188,34147358,31185481,26318357,27676708,31487012,고성
179,1439,17515,2024,강원도,양양군,합 계,34541917,33319781,30703715,27322258,24223622,24661946,26379386,32251221,29372839,25051829,26809758,29944522,양양

In [9]:
melted_df = pd.melt(gangwon_elect, id_vars=['years', '시도', '시군구', '계약종별','지점명'], 
                    value_vars=['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'], 
                    var_name='month', value_name='전력량')
melted_df['month'] = melted_df['month'].str.replace('월','',regex=True).astype(int)
melted_df['전력량'] = melted_df['전력량'].astype(int)
melted_df
melted_df.to_csv('./data/preprocessing/type_total_elect_gangwon.csv')

In [10]:
melted_df

      years   시도  시군구 계약종별 지점명  month        전력량
0      2017  강원도  춘천시  합 계  춘천      1  166196000
1      2017  강원도  원주시  합 계  원주      1  241954655
2      2017  강원도  강릉시  합 계  강릉      1  183639452
3      2017  강원도  동해시  합 계  동해      1  228309916
4      2017  강원도  태백시  합 계  태백      1   31585822
...     ...  ...  ...  ...  ..    ...        ...
2155   2024  강원도  화천군  합 계  화천     12   24406547
2156   2024  강원도  양구군  합 계   양     12   19957358
2157   2024  강원도  인제군  합 계  인제     12   32852904
2158   2024  강원도  고성군  합 계  고성     12   31487012
2159   2024  강원도  양양군  합 계  양양     12   29944522

[2160 rows x 7 columns]